name: "VPS Deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@v1.0.3
        name: "Service update and rebuild"
        with:
          host: "132.226.94.168"
          username: "ubuntu"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/controle_aluguel/controle-aluguel
            git pull origin main

            docker compose -f prod.yml build app
            docker compose -f prod.yml up -d app

            docker compose -f prod.yml exec -T app php artisan optimize
            docker compose -f prod.yml exec -T app php artisan migrate --force
            docker compose -f prod.yml exec -T app php artisan config:cache
            docker compose -f prod.yml exec -T app php artisan event:cache
            docker compose -f prod.yml exec -T app php artisan route:cache
            docker compose -f prod.yml exec -T app php artisan view:cache
